# -*- coding: utf-8 -*-
## File autogenerated by SQLAutoCode
## see http://code.google.com/p/sqlautocode/

from sqlalchemy import *
from sqlalchemy.databases.mysql import *

metadata = MetaData()


networks =  Table('networks', metadata,
    Column(u'created_at', DATETIME(), primary_key=False),
            Column(u'updated_at', DATETIME(), primary_key=False),
            Column(u'deleted_at', DATETIME(), primary_key=False),
            Column(u'id', INTEGER(), primary_key=True, nullable=False),
            Column(u'injected', Integer(), primary_key=False),
            Column(u'cidr', VARCHAR(length=43), primary_key=False),
            Column(u'netmask', VARCHAR(length=39), primary_key=False),
            Column(u'bridge', VARCHAR(length=255), primary_key=False),
            Column(u'gateway', VARCHAR(length=39), primary_key=False),
            Column(u'broadcast', VARCHAR(length=39), primary_key=False),
            Column(u'dns1', VARCHAR(length=39), primary_key=False),
            Column(u'vlan', INTEGER(), primary_key=False),
            Column(u'vpn_public_address', VARCHAR(length=39), primary_key=False),
            Column(u'vpn_public_port', INTEGER(), primary_key=False),
            Column(u'vpn_private_address', VARCHAR(length=39), primary_key=False),
            Column(u'dhcp_start', VARCHAR(length=39), primary_key=False),
            Column(u'project_id', VARCHAR(length=255), primary_key=False),
            Column(u'host', VARCHAR(length=255), primary_key=False),
            Column(u'cidr_v6', VARCHAR(length=43), primary_key=False),
            Column(u'gateway_v6', VARCHAR(length=39), primary_key=False),
            Column(u'label', VARCHAR(length=255), primary_key=False),
            Column(u'netmask_v6', VARCHAR(length=39), primary_key=False),
            Column(u'bridge_interface', VARCHAR(length=255), primary_key=False),
            Column(u'multi_host', Integer(), primary_key=False),
            Column(u'dns2', VARCHAR(length=39), primary_key=False),
            Column(u'uuid', VARCHAR(length=36), primary_key=False),
            Column(u'priority', INTEGER(), primary_key=False),
            Column(u'rxtx_base', INTEGER(), primary_key=False),
            Column(u'deleted', INTEGER(), primary_key=False),
            Column(u'mtu', INTEGER(), primary_key=False),
            Column(u'dhcp_server', VARCHAR(length=39), primary_key=False),
            Column(u'enable_dhcp', Integer(), primary_key=False),
            Column(u'share_address', Integer(), primary_key=False),
    
    
    )
Index(u'networks_bridge_deleted_idx', networks.c.bridge, networks.c.deleted, unique=False)
Index(u'networks_vlan_deleted_idx', networks.c.vlan, networks.c.deleted, unique=False)
Index(u'networks_host_idx', networks.c.host, unique=False)
Index(u'networks_project_id_deleted_idx', networks.c.project_id, networks.c.deleted, unique=False)
Index(u'networks_cidr_v6_idx', networks.c.cidr_v6, unique=False)
Index(u'uniq_networks0vlan0deleted', networks.c.vlan, networks.c.deleted, unique=True)
Index(u'networks_uuid_project_id_deleted_idx', networks.c.uuid, networks.c.project_id, networks.c.deleted, unique=False)

